FROM python:3.11-slim

# set python to not to write .pyc files
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

# install basic system dependencies required for potential runtime operations
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    cmake \
    curl \
    && rm -rf /var/lib/apt/lists/*

# forcing compilation of the llama.cpp library for CUDA cores
ENV CMAKE_ARGS="-DGGML_CUDA=on"
ENV FORCE_CMAKE=1

# Copy only requirements first to leverage Docker layer caching
COPY requirements.manager.txt .

# Install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.manager.txt 

COPY manager.py .

CMD ["sh", "-c", "uvicorn manager:app --host 0.0.0.0 --port ${MANAGER_PORT:-8001}"]
